### ISSUE TITLE
Direct model queries not cached?

### ISSUE THREAD

**Issue by sebastiaanluca** [rinvex/repository#103]
Noticed that method calls not found in the Eloquent or base repository are passed to the model, but that they're not cached. Is there any reason not to?

I tried the following code and it seems to work, but that's just a test of course.

```
/**
 * Dynamically pass missing methods to the model.
 *
 * @param string $method
 * @param array $parameters
 *
 * @return mixed
 */
public function __call($method, $parameters)
{
    return $this->executeCallback(get_called_class(), __FUNCTION__, func_get_args(), function() use($method, $parameters) {
        return call_user_func_array(['parent', $method], $parameters);
    });
}
```

And perhaps an entirely different issue, but caching is applied manually in each method at the moment. IMO this could be optimized by using a cache decorator and even using a technique (of which I forgot its name 🤐) that caches a method call and its parameters by a unique hash. I implemented this a while ago in my own repositories I then used and works like a charm. It allows you to cache __every__ query and it's pretty simple to apply.

**Comment by Omranic** [comment]
Yes, direct model queries isn't cached by default since you can do almost unpredictable things with the underlying model which maybe or maybe not Eloquent, so it's up to the developer to cache everything like your example above, or stick to the default.

By the way, I'm open to any ideas in simplifying the implementation, so please feel free to propose your better solutions or maybe send a PR 😉
