### ISSUE TITLE
Change repositoryId dynamically

### ISSUE THREAD

**Issue by ahmadazimi** [rinvex/repository#109]
Hi there,

Thank you for this great library ;-)

I'm currently working on a complicated application using Laravel 5.3 and also Rinvex Repository and I need your suggestion about caching queries.

In my case, I should generate repositoryId in some cases. This is how I've implemented my extended repository class:

```php
public function getRepositoryId()
{
    $framework = app(Framework::class);

    if ( ! $framework->is_campaign_enabled) {
        return $this->repositoryId;
    }

    if ($framework->campaign_slug === 'me') {
        /** @var User $user */
        $user = Auth::user();

        return $this->repositoryId.'.'.$user->getAttribute('id');
    }

    return $this->repositoryId.'.'.$framework->campaign_slug;
}
```

Is this a correct way?
And is there any performance issue in this solution?

**Comment by ahmadazimi** [comment]
I've found the first problem with this solution!

I can not use **forgetCache** to delete entire repository cache.

**Comment by Omranic** [comment]
I can't see the benefit or use case for such scenario, maybe you could explain your goals so we can advice better. Anyway, repositories for same entity must not changed, otherwise it will be considered a different entity, and therefore cache won't work as you expect since it will be stored with inconsistent IDs, other issues may arise!
