### ISSUE TITLE
Add tag/branch for Laravel 5.5 (resupport)

### ISSUE THREAD

**Issue by tprj29** [rinvex/repository#172]
# Add tag/branch for Laravel 5.5 (resupport)
I'm using your package in one of my projects. Recently i wanted to updated my dependencies and noticed this package is no longer supporting Laravel5.5 on the branch **dev-develop**. My question to you is, can you make a separate **branch** or add a **tag** so i can require your package again in my dependencies. 

Hope to hear from you soon, this is causing me trouble in my develop cycle atm.

**Comment by Omranic** [comment]
Here you go 072c27c08173bca746c23816a09ef1267432767d 🙂

I re-thought this and concluded that since there's still no ETA on when to merge into master, and sicne this is a development branch, we can keep backward compatibility for now. Hopefully things will be stabilized soon & we're able to tag a gold release. Thanks for all your patience!
