### ISSUE TITLE
[Proposal] UpdateOrCreate, should be in the repository?

### ISSUE THREAD

**Issue by ricardovigatti** [rinvex/repository#99]
Since Eloquent already handle this method, do you think it's a good idea to handle it at the repository too?

**Comment by Omranic** [comment]
I'm not sure if we've to implement it explicitly, since no added benefit as per my understanding now. Please remember that you've full access to the underlying model through the magic `__call` & `__callStatic` methods, so you actually can call `UpdateOrCreate` on the repository & it will get passed transparently to the model 😃
